[package]
name = "arc-cli"
version = "0.1.0"
edition = "2024"

[dependencies]
aws-config = "1.8.12"
aws-runtime = "1.5.17"
aws-types = "1.3.11"
clap = { version = "4.5.53", features = ["derive"] }
cliclack = "0.3.7"
pollster = "0.4.0"
topo_sort = "0.4.0"

[[bin]]
name = "arc"
path = "src/main.rs"